/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	snapshotmetadataservicev1beta1 "github.com/kubernetes-csi/external-snapshot-metadata/client/apis/snapshotmetadataservice/v1beta1"
	scheme "github.com/kubernetes-csi/external-snapshot-metadata/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SnapshotMetadataServicesGetter has a method to return a SnapshotMetadataServiceInterface.
// A group's client should implement this interface.
type SnapshotMetadataServicesGetter interface {
	SnapshotMetadataServices() SnapshotMetadataServiceInterface
}

// SnapshotMetadataServiceInterface has methods to work with SnapshotMetadataService resources.
type SnapshotMetadataServiceInterface interface {
	Create(ctx context.Context, snapshotMetadataService *snapshotmetadataservicev1beta1.SnapshotMetadataService, opts v1.CreateOptions) (*snapshotmetadataservicev1beta1.SnapshotMetadataService, error)
	Update(ctx context.Context, snapshotMetadataService *snapshotmetadataservicev1beta1.SnapshotMetadataService, opts v1.UpdateOptions) (*snapshotmetadataservicev1beta1.SnapshotMetadataService, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*snapshotmetadataservicev1beta1.SnapshotMetadataService, error)
	List(ctx context.Context, opts v1.ListOptions) (*snapshotmetadataservicev1beta1.SnapshotMetadataServiceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *snapshotmetadataservicev1beta1.SnapshotMetadataService, err error)
	SnapshotMetadataServiceExpansion
}

// snapshotMetadataServices implements SnapshotMetadataServiceInterface
type snapshotMetadataServices struct {
	*gentype.ClientWithList[*snapshotmetadataservicev1beta1.SnapshotMetadataService, *snapshotmetadataservicev1beta1.SnapshotMetadataServiceList]
}

// newSnapshotMetadataServices returns a SnapshotMetadataServices
func newSnapshotMetadataServices(c *CbtV1beta1Client) *snapshotMetadataServices {
	return &snapshotMetadataServices{
		gentype.NewClientWithList[*snapshotmetadataservicev1beta1.SnapshotMetadataService, *snapshotmetadataservicev1beta1.SnapshotMetadataServiceList](
			"snapshotmetadataservices",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *snapshotmetadataservicev1beta1.SnapshotMetadataService {
				return &snapshotmetadataservicev1beta1.SnapshotMetadataService{}
			},
			func() *snapshotmetadataservicev1beta1.SnapshotMetadataServiceList {
				return &snapshotmetadataservicev1beta1.SnapshotMetadataServiceList{}
			},
		),
	}
}
