/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/kubernetes-csi/external-snapshot-metadata/client/apis/snapshotmetadataservice/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// SnapshotMetadataServiceLister helps list SnapshotMetadataServices.
// All objects returned here must be treated as read-only.
type SnapshotMetadataServiceLister interface {
	// List lists all SnapshotMetadataServices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.SnapshotMetadataService, err error)
	// Get retrieves the SnapshotMetadataService from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.SnapshotMetadataService, error)
	SnapshotMetadataServiceListerExpansion
}

// snapshotMetadataServiceLister implements the SnapshotMetadataServiceLister interface.
type snapshotMetadataServiceLister struct {
	indexer cache.Indexer
}

// NewSnapshotMetadataServiceLister returns a new SnapshotMetadataServiceLister.
func NewSnapshotMetadataServiceLister(indexer cache.Indexer) SnapshotMetadataServiceLister {
	return &snapshotMetadataServiceLister{indexer: indexer}
}

// List lists all SnapshotMetadataServices in the indexer.
func (s *snapshotMetadataServiceLister) List(selector labels.Selector) (ret []*v1beta1.SnapshotMetadataService, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.SnapshotMetadataService))
	})
	return ret, err
}

// Get retrieves the SnapshotMetadataService from the index for a given name.
func (s *snapshotMetadataServiceLister) Get(name string) (*v1beta1.SnapshotMetadataService, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("snapshotmetadataservice"), name)
	}
	return obj.(*v1beta1.SnapshotMetadataService), nil
}
