/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	apissnapshotmetadataservicev1beta1 "github.com/kubernetes-csi/external-snapshot-metadata/client/apis/snapshotmetadataservice/v1beta1"
	versioned "github.com/kubernetes-csi/external-snapshot-metadata/client/clientset/versioned"
	internalinterfaces "github.com/kubernetes-csi/external-snapshot-metadata/client/informers/externalversions/internalinterfaces"
	snapshotmetadataservicev1beta1 "github.com/kubernetes-csi/external-snapshot-metadata/client/listers/snapshotmetadataservice/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SnapshotMetadataServiceInformer provides access to a shared informer and lister for
// SnapshotMetadataServices.
type SnapshotMetadataServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() snapshotmetadataservicev1beta1.SnapshotMetadataServiceLister
}

type snapshotMetadataServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewSnapshotMetadataServiceInformer constructs a new informer for SnapshotMetadataService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSnapshotMetadataServiceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewSnapshotMetadataServiceInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewFilteredSnapshotMetadataServiceInformer constructs a new informer for SnapshotMetadataService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSnapshotMetadataServiceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewSnapshotMetadataServiceInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewSnapshotMetadataServiceInformerWithOptions constructs a new informer for SnapshotMetadataService type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSnapshotMetadataServiceInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	gvr := schema.GroupVersionResource{Group: "cbt.storage.k8s.io", Version: "v1beta1", Resource: "snapshotmetadataservices"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CbtV1beta1().SnapshotMetadataServices().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CbtV1beta1().SnapshotMetadataServices().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CbtV1beta1().SnapshotMetadataServices().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CbtV1beta1().SnapshotMetadataServices().Watch(ctx, opts)
			},
		}, client),
		&apissnapshotmetadataservicev1beta1.SnapshotMetadataService{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	)
}

func (f *snapshotMetadataServiceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewSnapshotMetadataServiceInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *snapshotMetadataServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apissnapshotmetadataservicev1beta1.SnapshotMetadataService{}, f.defaultInformer)
}

func (f *snapshotMetadataServiceInformer) Lister() snapshotmetadataservicev1beta1.SnapshotMetadataServiceLister {
	return snapshotmetadataservicev1beta1.NewSnapshotMetadataServiceLister(f.Informer().GetIndexer())
}
